-- CreateTable
CREATE TABLE "Order" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "admin_graphql_api_id" TEXT NOT NULL,
    "app_id" TEXT,
    "browser_ip" TEXT,
    "buyer_accepts_marketing" BOOLEAN NOT NULL,
    "cancel_reason" TEXT,
    "cancelled_at" TEXT,
    "cart_token" TEXT,
    "checkout_id" TEXT,
    "checkout_token" TEXT,
    "client_details" TEXT,
    "closed_at" TEXT,
    "confirmation_number" TEXT,
    "confirmed" BOOLEAN NOT NULL,
    "contact_email" TEXT,
    "created_at" TEXT,
    "currency" TEXT,
    "current_subtotal_price" TEXT,
    "current_subtotal_price_set" TEXT,
    "current_total_additional_fees_set" TEXT,
    "current_total_discounts" TEXT,
    "current_total_discounts_set" TEXT,
    "current_total_duties_set" TEXT,
    "current_total_price" TEXT,
    "current_total_price_set" TEXT,
    "current_total_tax" TEXT,
    "current_total_tax_set" TEXT,
    "customer_locale" TEXT,
    "device_id" TEXT,
    "discount_codes" TEXT NOT NULL,
    "email" TEXT,
    "estimated_taxes" BOOLEAN NOT NULL,
    "financial_status" TEXT,
    "fulfillment_status" TEXT,
    "landing_site" TEXT,
    "landing_site_ref" TEXT,
    "location_id" TEXT,
    "merchant_of_record_app_id" TEXT,
    "name" TEXT,
    "note" TEXT,
    "note_attributes" TEXT NOT NULL,
    "number" INTEGER NOT NULL,
    "order_number" INTEGER NOT NULL,
    "order_status_url" TEXT,
    "original_total_additional_fees_set" TEXT,
    "original_total_duties_set" TEXT,
    "payment_gateway_names" TEXT NOT NULL,
    "phone" TEXT,
    "po_number" TEXT,
    "presentment_currency" TEXT,
    "processed_at" TEXT,
    "reference" TEXT,
    "referring_site" TEXT,
    "source_identifier" TEXT,
    "source_name" TEXT,
    "source_url" TEXT,
    "subtotal_price" TEXT,
    "subtotal_price_set" TEXT,
    "tags" TEXT,
    "tax_exempt" BOOLEAN NOT NULL,
    "tax_lines" TEXT NOT NULL,
    "taxes_included" BOOLEAN NOT NULL,
    "test" BOOLEAN NOT NULL,
    "token" TEXT,
    "total_discounts" TEXT,
    "total_discounts_set" TEXT,
    "total_line_items_price" TEXT,
    "total_line_items_price_set" TEXT,
    "total_outstanding" TEXT,
    "total_price" TEXT,
    "total_price_set" TEXT,
    "total_shipping_price_set" TEXT,
    "total_tax" TEXT,
    "total_tax_set" TEXT,
    "total_tip_received" TEXT,
    "total_weight" INTEGER NOT NULL,
    "updated_at" TEXT,
    "user_id" TEXT,
    "webhookId" TEXT,
    "apiVersion" TEXT,
    "billing_address_id" INTEGER,
    "customer_id" INTEGER,
    "payment_terms" TEXT,
    "shipping_address_id" INTEGER NOT NULL,
    CONSTRAINT "Order_billing_address_id_fkey" FOREIGN KEY ("billing_address_id") REFERENCES "Address" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Order_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "Customer" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Order_shipping_address_id_fkey" FOREIGN KEY ("shipping_address_id") REFERENCES "Address" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Address" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "first_name" TEXT NOT NULL,
    "address1" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "zip" TEXT NOT NULL,
    "province" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "address2" TEXT,
    "company" TEXT,
    "latitude" REAL,
    "longitude" REAL,
    "name" TEXT NOT NULL,
    "country_code" TEXT NOT NULL,
    "province_code" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Customer" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL,
    "accepts_marketing" BOOLEAN NOT NULL,
    "created_at" TEXT,
    "updated_at" TEXT,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "note" TEXT,
    "verified_email" BOOLEAN NOT NULL,
    "multipass_identifier" TEXT,
    "tax_exempt" BOOLEAN NOT NULL,
    "phone" TEXT,
    "email_marketing_consent" TEXT NOT NULL,
    "sms_marketing_consent" TEXT,
    "tags" TEXT,
    "currency" TEXT NOT NULL,
    "accepts_marketing_updated_at" TEXT,
    "marketing_opt_in_level" TEXT,
    "tax_exemptions" TEXT NOT NULL,
    "admin_graphql_api_id" TEXT NOT NULL,
    "default_address_id" INTEGER NOT NULL,
    CONSTRAINT "Customer_default_address_id_fkey" FOREIGN KEY ("default_address_id") REFERENCES "Address" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "LineItem" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "admin_graphql_api_id" TEXT NOT NULL,
    "attributed_staffs" TEXT NOT NULL,
    "fulfillable_quantity" INTEGER NOT NULL,
    "fulfillment_service" TEXT,
    "fulfillment_status" TEXT,
    "gift_card" BOOLEAN NOT NULL,
    "grams" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "price" TEXT NOT NULL,
    "price_set" TEXT,
    "product_exists" BOOLEAN NOT NULL,
    "product_id" INTEGER NOT NULL,
    "properties" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "requires_shipping" BOOLEAN NOT NULL,
    "sku" TEXT NOT NULL,
    "taxable" BOOLEAN NOT NULL,
    "title" TEXT NOT NULL,
    "total_discount" TEXT NOT NULL,
    "total_discount_set" TEXT,
    "variant_id" INTEGER NOT NULL,
    "variant_inventory_management" TEXT,
    "variant_title" TEXT,
    "vendor" TEXT,
    "tax_lines" TEXT NOT NULL,
    "duties" TEXT NOT NULL,
    "discount_allocations" TEXT NOT NULL,
    "order_id" INTEGER NOT NULL,
    CONSTRAINT "LineItem_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "Order" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ShippingLine" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "carrier_identifier" TEXT,
    "code" TEXT,
    "discounted_price" TEXT,
    "discounted_price_set" TEXT,
    "phone" TEXT,
    "price" TEXT,
    "price_set" TEXT,
    "requested_fulfillment_service_id" TEXT,
    "source" TEXT,
    "title" TEXT,
    "tax_lines" TEXT NOT NULL,
    "discount_allocations" TEXT,
    "order_id" INTEGER NOT NULL,
    CONSTRAINT "ShippingLine_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "Order" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
